# Generated by Django 3.1.5 on 2021-11-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('dish', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
