# Generated by Django 3.1.5 on 2021-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0002_orderfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='restname',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
