# Generated by Django 3.1.5 on 2021-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0003_orderfood_restname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='restname',
            field=models.CharField(max_length=140),
        ),
    ]
