# Generated by Django 3.1.5 on 2021-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0004_auto_20211114_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=500)),
                ('phoneno', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
