# Generated by Django 3.1.5 on 2021-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0005_resturantdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
