# Generated by Django 3.1.5 on 2021-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0006_auto_20211114_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
