# Generated by Django 3.1.5 on 2021-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystemapp', '0007_auto_20211114_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfooditems',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=500)),
                ('dishname', models.CharField(max_length=500)),
                ('qty', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
